version: '3.8'

services:
  twingate-connector:
    image: twingate/connector:1
    container_name: twingate-connector
    restart: unless-stopped
    environment:
      TWINGATE_ACCESS_TOKEN: ${TWINGATE_ACCESS_TOKEN}
      TWINGATE_REFRESH_TOKEN: ${TWINGATE_REFRESH_TOKEN}
      TWINGATE_NETWORK: ${TWINGATE_NETWORK}
      TWINGATE_LOG_LEVEL: ${TWINGATE_LOG_LEVEL:-3}
      TWINGATE_LOG_ANALYTICS: ${TWINGATE_LOG_ANALYTICS:-v1}
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
