services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10
      EULA: "TRUE"
      MEMORY: '12G'
      ENABLE_ROLLING_LOGS: 'true'
      USE_AIKAR_FLAGS: 'true'
    volumes:
      - /opt/atm10/data:/data