services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80/tcp' # Web interface on port 8080
    environment:
      TZ: 'Africa/Johannesburg'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      PIHOLE_DNS_: '8.8.8.8;8.8.4.4'
      DNSSEC: 'true'
      CONDITIONAL_FORWARDING: 'true'
      CONDITIONAL_FORWARDING_IP: '192.168.50.1'
      CONDITIONAL_FORWARDING_DOMAIN: 'local'
      CONDITIONAL_FORWARDING_REVERSE: '50.168.192.in-addr.arpa'
      VIRTUAL_HOST: 'pihole.smet-server.ddns.net'
      TEMPERATUREUNIT: 'c'
      QUERY_LOGGING: 'true'
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required for some Pi-hole functionality
    restart: unless-stopped
    networks:
      - pihole-net

networks:
  pihole-net:
    driver: bridge
