version: '3.8'

services:
  rustdesk-server:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-server
    restart: unless-stopped
    command: hbbs -r rustdesk-relay:21117
    environment:
      - RUST_LOG=info
    ports:
      - '21115:21115' # NAT type test (public)
      - '21116:21116' # ID/Rendezvous server (public)
      - '21116:21116/udp' # ID/Rendezvous server UDP (public)
      - '21118:21118' # Web console (Twingate only)
    volumes:
      - /srv/docker/rustdesk/data:/root
    networks:
      - rustdesk-net

  rustdesk-relay:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-relay
    restart: unless-stopped
    command: hbbr
    environment:
      - RUST_LOG=info
    ports:
      - '21117:21117' # Relay server (public)
    volumes:
      - /srv/docker/rustdesk/data:/root
    networks:
      - rustdesk-net

networks:
  rustdesk-net:
    driver: bridge
